# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaults: &defaults
  docker:
   - image: circleci/node:13.8.0 

commands:
  print_pipeline_id:
     steps:
       - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  save_hello_world_output:
    <<: *defaults
    steps:
      - checkout
      - print_pipeline_id
      - run:
          echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          cat ~/output.txt
  fail_job:
    <<: *defaults
    steps: 
      - run: echo "who run the world"
      

  workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
           requires:
             - save_hello_world_output