# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
contain: &contain
  docker:
   - image: circleci/node:13.8.0 
commands:
  print_pipeline_id:
     steps:
       - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  save_hello_world_output:
    <<: *contain
    steps:
      - checkout
      - print_pipeline_id
      - run:
          echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    <<: *contain
    steps:
      - attach_workspace:
          at: ~/
      - run:
          cat ~/output.txt
  fail_job:
    <<: *contain
    steps: 
      - run: echo "who run the
      - run: 
          name: error1
          command: echo "Here's an error"
          when: on_fail 
    workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
           requires:
             - save_hello_world_output